### ISSUE TITLE
How does decpac determine what goes in the conf file?

### ISSUE THREAD

**Issue by crinklywrappr** [rendaw/decpac#8]
This may not be a bug.  I noticed earlier today that curl was missing from the decpac.conf

![image](https://user-images.githubusercontent.com/56522/90600207-c3e63780-e1bb-11ea-9b34-bf952ba2a682.png)

**Comment by rendaw** [comment]
Generate roughly includes the stuff in `pacman -Qe`, so if curl is added or removed would depend on if other packages that have been explicitly installed require it.

I checked on my system and `curl` isn't in `pacman -Qe` so I guess there's something else (and more likely a bunch of things since it's a common util) that pull it in as a dependency.

FWIW if you add it to `decpac.conf` yourself it will guarantee it's on the system regardless of other packages.
